version: '3.8'

services:
  mydb:
    image: mydb:latest
    environment:
      - MYSQL_HOST=db-stage-db.mysql.database.azure.com
      - MYSQL_USER=KhaoulaRajhi
      - MYSQL_PASSWORD=203JFT1612db
      - MYSQL_DB=stage
      - MYSQL_PORT=3306
    ports:
      - "8080:8080"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 203JFT1612db
      MYSQL_DATABASE: stage
      MYSQL_USER: KhaoulaRajhi
      MYSQL_PASSWORD: 203JFT1612db
    ports:
      - "3306:3306"

  springprojectt-app:
    depends_on:
      - mydb
    image: khaoularajhi/springprojectt:latest
    container_name: springprojectt-app
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db-stage-db.mysql.database.azure.com:3306/stage?useSSL=true&requireSSL=false",
        "spring.datasource.username" : "KhaoulaRajhi",
        "spring.datasource.password" : "203JFT1612db",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angularproject-app:
    #The docker file in FE, builds and provides the docker image.
    image: khaoularajhi/angularproject:latest
    ports:
      - 4200:4200 #Forwars the exposed port 4200 on the container to port 4200 on the host machine
    links: 
      - springprojectt-app

volumes:
  db:
