version: '3.8'

services:
  springprojectt-app:
    image: khaoularajhi/springprojectt:latest
    container_name: springprojectt-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db-stage-db.mysql.database.azure.com:3306/stage?useSSL=true&requireSSL=false",
        "spring.datasource.username" : "KhaoulaRajhi",
        "spring.datasource.password" : "203JFT1612db",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  angularproject-app:
    #The docker file in FE, builds and provides the docker image.
    image: khaoularajhi/angularproject:latest
    ports:
      - 4200:4200 #Forwars the exposed port 4200 on the container to port 4200 on the host machine
    links: 
      - springprojectt-app
